site_name: whatlies
nav:
  - Home: index.md
  - What Are Embeddings: tutorial/embeddings.md
  - Chaining Operations: index.md
  - Language Options: index.md
  - API:
    - Embedding: api/embedding.md
    - EmbeddingSet: api/embeddingset.md
    - Transformers: api/transformers.md
    - Language: api/language.md
plugins:
  - mkdocstrings
theme:
  name: material
  palette:
    primary: white
    accent: purple