site_name: whatlies
nav:
  - Home: /whatlies
  - Getting Started:
    - 1. Embeddings: intro-with-tokens-render.ipynb
    - 2. EmbeddingSets: towards-embeddings-render.ipynb
    - 3. Transform and Interact: towards-embeddings-render.ipynb
    - 4. Contexual Embeddings: embeddings-with-context-render.ipynb
    - 5. Languages: selecting-backends-render.ipynb
plugins:
  - mkdocs-jupyter
theme:
  name: material
  palette:
    primary: white
    accent: purple