site_name: whatlies
nav:
  - Home: /whatlies
  - Getting Started:
    - 1. Embeddings: intro-with-tokens-render.ipynb
    - 2. EmbeddingSets: towards-embeddings-render.ipynb
    - 3. Contexual Embeddings: embeddings-with-context-render.ipynb
    - 4. Selecting Backends: selecting-backends-render.ipynb
    - 5. Transformations: other-transformations-render.ipynb
    - 6. Visualisations: other-visualisations-render.ipynb

plugins:
  - mkdocs-jupyter
theme:
  name: material
  palette:
    primary: white
    accent: purple